# Enable deep sleep support
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Bluetooth Experimental 
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Test for BIOS boot
CONFIG_ZMK_USB_BOOT=y

# Debounce time for key press in milliseconds (Default: 5)
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10

# Debounce time for key release in milliseconds (Default: 5)
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10
